columnSuffix: null
contentColumnType: string
fieldGroup: ae727592-cdcb-464b-824c-a2aefc697ada # Homepage
handle: heroImage
instructions: null
name: 'Hero Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:70e6fcab-0d35-4b12-89a1-47822b74bd85' # Base
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:70e6fcab-0d35-4b12-89a1-47822b74bd85' # Base
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
